{% set name = "flufl.lock" %}
{% set version = "8.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flufl_lock-{{ version }}.tar.gz
  sha256: 15b333c35fab1a36b223840057258aeb4cd79f0fbaf82c144f23cdf6cf14d5e3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - hatchling
    - pip
    - python >=3.8
  run:
    - atpublic
    - psutil
    - python >=3.8

test:
  imports:
    - flufl
    - flufl.lock
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://flufllock.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: NFS-safe file locking with timeouts for POSIX and Windows
  doc_url: https://flufllock.readthedocs.io
  dev_url: https://gitlab.com/warsaw/flufl.lock

extra:
  recipe-maintainers:
    - johanneskoester
    - efiop
