{% set name = "flufl.lock" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flufl_lock-{{ version }}.tar.gz
  sha256: d88302005692a63d98b60080158faf089be5ecae6969f706409da8276fdce7cb

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - hatchling
    - pip
    - python {{ python_min }}
  run:
    - atpublic
    - psutil
    - python >={{ python_min }}

test:
  imports:
    - flufl
    - flufl.lock
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://flufllock.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: NFS-safe file locking with timeouts for POSIX and Windows
  doc_url: https://flufllock.readthedocs.io
  dev_url: https://gitlab.com/warsaw/flufl.lock

extra:
  recipe-maintainers:
    - johanneskoester
    - efiop
